[package]
name = "streamline"
version = "0.1.0"
authors = ["Alex Pearson <alex@alexpear.com>"]
edition = "2018"
license = "MIT"

[lib]
doctest = false
test = false

[dependencies]
async-trait = "0.1.27"
futures = "0.3.4"

[dev-dependencies.tokio]
default-features = false
version = "0.2.13"
